app01/urls.py
from django.conf.urls import url
from app01.views import *

urlpatterns = [

]

web01/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from app01 import views

urlpatterns = [
    url(r'^app01/',include('app01.urls')),
    url(r'^app02/',include('app02.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^index',views.index),
    url(r'^api/',views.api,),
    url(r'^add/',views.add1,),
    url(r'^edit/',views.edit,),
    url(r'^del/',views.adel,),
    url(r'^assetinfo/',views.assetinfo,),
    url(r'^test/',views.test,),
    url(r'^zichan/',views.zichan,),
    url(r'^page/([0-9][0-9])/$',views.fenye,),
    url(r'^page/([0-9][0-9][0-9])/$',views.fenye,),
    url(r'^page/([0-9])/$',views.fenye,),
    url(r'^asset/',views.asset1,),
    url(r'^apiinfo/',views.apiinfo,),
    url(r'^login/',views.login,),
    url(r'^logout/',views.logout,),
    url(r'^apiorder/',views.aprorder,),
    url(r'^search/',views.search,),
    url(r'^weixin/',views.weixin,),
]

app01/models.py
#!coding:utf-8
from django.db import models
# Create your models here.
from django.db import models


class AssetType(models.Model):
    Asset_type = models.CharField(max_length=20)

class dept(models.Model):
    dept_name = models.CharField(max_length=50)

class Aunit(models.Model):
    unit_name = models.CharField(max_length=5)

class Asset(models.Model):
    dept_choice = (
        (u'1', '销售部'),
        (u'2', '采购部'),
        (u'3', '信息技术部'),
        (u'4', '客服部'),
        (u'5', '市场部'),
        (u'6', '事业加盟部'),
        (u'7', '战略研究部'),
        (u'8', '人事行政部'),
        (u'9', '财务部'),
        (u'10', '仓储配送部'),
    )
    Dname = models.CharField(max_length=2,choices = dept_choice)
    asset_type = (
        (u'1', '笔记本电脑'),
        (u'2', 'MOTO无线基站'),
        (u'3', 'UPS电源'),
        (u'4', '标签打印机'),
        (u'5', '传真机'),
        (u'6', '打印机'),
        (u'7', '大型存储设备'),
        (u'8', '服务器'),
        (u'9', '服务器机柜'),
        (u'10', '交换机'),
        (u'11', '扫描枪'),
        (u'12', '扫描仪'),
        (u'13', '台式电脑'),
        (u'14', '条码打印机'),
        (u'15', '投影仪'),
        (u'16', '投影仪幕布'),
        (u'17', '网络设备'),
        (u'18', '无动力筒机'),
        (u'19', '显示器'),
        (u'20', '针式打印机'),
    )
    Atype = models.CharField(max_length=2, choices=asset_type)
    Status_type = (
        (u'1','在用'),
        (u'0','闲置')
    )
    Status = models.CharField(max_length=2,choices=Status_type)
    Zcbh = models.CharField(max_length=30)
    Bgr = models.CharField(max_length=30)
    Brand = models.CharField(max_length=200)
    Aunit = models.CharField(max_length=10)
    Count = models.IntegerField()
    Price = models.FloatField()

    gtime = models.DateField()
    def __str__(self):
        return self.Bgr


class user(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)


class apiorder(models.Model):
    Apiname = models.CharField(max_length=50)
    worder = models.CharField(max_length=10)
    horder = models.CharField(max_length=10)
    yorder = models.CharField(max_length=10)
    product = models.CharField(max_length=10)

templates/api.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>api-site</title>
</head>
<body>
<h2>API站点管理</h2>
<form action="http://127.0.0.1:8000/api/" method="post">
<select name="apisite">
    <option  value="BengBu_Inside">蚌埠</option>
    <option  value="GuoTou_Inside">国投</option>
</select>
<select name="action">
    <option  value="start">开启</option>
    <option  value="stop">关闭</option>
</select>
    <br>
    <input type="submit" value="执行">
</form>
<img href="static/assets/css/img/bei.png" alt="hha">

</body>
</html>

templates/apiinfo.html
<!DOCTYPE HTML>
<html>
 <head>
  <title>API简介</title>
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
       <link href="static/assets/css/dpl-min.css" rel="stylesheet" type="text/css" />
    <link href="static/assets/css/bui-min.css" rel="stylesheet" type="text/css" />
    <link href="static/assets/css/page-min.css" rel="stylesheet" type="text/css" />   <!-- 下面的样式，仅是为了显示代码，而不应该在项目中使用-->
   <link href="static/assets/css/prettify.css" rel="stylesheet" type="text/css" />
   <style type="text/css">
    code {
      padding: 0px 4px;
      color: #d14;
      background-color: #f7f7f9;
      border: 1px solid #e1e1e8;
    }
   </style>
 </head>
 <body>
  
  <div class="container">
    <div class="row">
      <div class="span24">
        <h2>简介</h2>
        <p>API分一下几种类型</p>
        <ol>
          <li>对内接口，为业务接口提供基础服务的，比如，邮件接口、物流接口、发送API订单至ERP接口</li>
          <li>业务接口，给客户提供服务的接口，比如，广东政采接口、宝钢接口</li>
        </ol>
      </div>
    </div>
    <div class="row">
      <div class="span16">
        <h3>API服务器</h3>
        <p>两台ESXI，三个虚拟机</p>
        <ol>
          <li>API01:10.10.210.171</li>
          <li>API02:10.10.210.172</li>
          <li>APIJOB:10.10.210.131</li>
        </ol>
      </div>
    </div>
    <div class="row">
      <div class="span16">
        <h3>APIjob</h3>
        <p>每个API都有自己job</p>
        <ol>
          <li>商品联动</li>
          <li>发送价套</li>
          <li>拉去对方订单</li>
          <li>发送订单到ERP</li>
        </ol>
      </div>
    </div>
  </div>
  <script type="text/javascript" src="static/assets/js/jquery-1.8.1.min.js"></script>
  <script type="text/javascript" src="static/assets/js/bui-min.js"></script>

  <script type="text/javascript" src="static/assets/js/config-min.js"></script>
  <script type="text/javascript">
    BUI.use('common/page');
  </script>
  <!-- 仅仅为了显示代码使用，不要在项目中引入使用-->
  <script type="text/javascript" src="static/assets/js/prettify.js"></script>
  <script type="text/javascript">
    $(function () {
      prettyPrint();
    });
  </script> 

<body>
</html>  

templates/asset_add.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="/static/Css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="/static/Css/bootstrap-responsive.css" />
    <link rel="stylesheet" type="text/css" href="/static/Css/style.css" />
    <script type="text/javascript" src="/static/Js/jquery.js"></script>
    <script type="text/javascript" src="/static/Js/jquery.sorted.js"></script>
    <script type="text/javascript" src="/static/Js/bootstrap.js"></script>
    <script type="text/javascript" src="/static/Js/ckform.js"></script>
    <script type="text/javascript" src="/static/Js/common.js"></script>

    <style type="text/css">
        body {
            padding-bottom: 40px;
        }
        .sidebar-nav {
            padding: 9px 0;
        }

        @media (max-width: 980px) {
            /* Enable use of floated navbar text */
            .navbar-text.pull-right {
                float: none;
                padding-left: 5px;
                padding-right: 5px;
            }
        }


    </style>
</head>
<body>
<form action="/add/" method="post" class="definewidth m20">
<table class="table table-bordered table-hover m10">
    <tr>
        <td width="10%" class="tableleft">部门</td>
        <td>
            <select name="dname_id">
            <option value="0">销售部</option><option value='1'/>信息技术部</option><option value='2'/>客服部</option>
			</select>
        </td>
    </tr>
	    <tr>
        <td class="tableleft">资产类型</td>
        <td><input type="text" name="atype"/></td>
    </tr>
    <tr>
        <td class="tableleft">资产编号</td>
        <td><input type="text" name="zcbh"/></td>
    </tr>
    <tr>
        <td class="tableleft">保管人</td>
        <td><input type="text" name="bgr"/></td>
    </tr>
    <tr>
        <td class="tableleft">品牌</td>
        <td><input type="text" name="brand"/></td>
    </tr>
    <tr>
        <td class="tableleft">价格</td>
        <td><input type="text" name="price"/></td>
    </tr>
	<tr>
        <td class="tableleft">单位</td>
        <td><input type="text" name="aunit"/></td>
    </tr>
	<tr>
        <td class="tableleft">数量</td>
        <td><input type="text" name="count"/></td>
    </tr>
    	<tr>
        <td class="tableleft">购进时间</td>
        <td><input type="date" name="gdate"/></td>
    </tr>
    <tr>
        <td class="tableleft">状态</td>
        <td>
            <input type="radio" name="status" value="0" checked/> 在用
            <input type="radio" name="status" value="1"/> 闲置
        </td>
    </tr>
    <tr>
        <td class="tableleft"></td>
        <td>
            <button type="submit" class="btn btn-primary" type="button">保存</button> &nbsp;&nbsp;<button type="button" class="btn btn-success" name="backid" id="backid">返回列表</button>
        </td>
    </tr>
</table>
</form>
</body>
</html>
<script>
    $(function () {       
		$('#backid').click(function(){
				window.location.href="index.html";
		 });

    });
</script>

templates/pc.html
<head>

       <link rel="stylesheet" type="text/css" href=/static/assets/css/boot3.css />
    <link rel="stylesheet" type="text/css" href= /static/Css/bootstrap-responsive.css/>
    <link rel="stylesheet" type="text/css" href=/static/Css/style.css />
    <script type="text/javascript" src=/static/assets/js/jquery.js></script>
    <style>
        .table{
            font-size: 5px;
        }
               .tab{
            width: 152px;
            height: 23px;
        }
        #test{
            position: absolute;
            left: 302px;
            top: 167px;
            width: 50%;
            height: 50%;
            background-color: #F0F0F0;
            display: none;
            opacity: 1;

        }
         .modal-content{
            position: absolute;
            left: 392px;
            top: 187px;
            width: 30%;
            height: 25%;
            opacity: 1;
            display: none;

        }

    </style>
</head>

<div  class="span13">
<form class="form-inline definewidth m20" action="/search/" method="post">
    <div class="search">
    <select class="selectpicker" name="tiaojian" style="width: 87px;height: 24px">
         <option value="b">保管人</option>
         <option value="z">资产编号</option>
    </select>
     {{ mes }}
    </div>
   <div>
    <input type="text" name="username" id="username"class="abc input-default" placeholder="" value="">&nbsp;&nbsp;
    <button id="search" type="submit" class="btn btn-primary">查询</button>&nbsp;&nbsp;
    <button type="button" class="btn btn-success" id="addnew"><a style="text-decoration: none;color:#e6f2ff" href="http://127.0.0.1:8000/add/">新增资产</a></button>
   </div>
</form>
<table class="table table-bordered table-hover definewidth m10" >
    <thead>
    <tr>
        <th>ID</th>
        <th>资产标签</th>
        <th>保管人</th>
        <th>品牌</th>
        <th>数量</th>
        <th>资产原值</th>
        <th>使用状态</th>
        <th>购进时间</th>
        <th>资产类型</th>
        <th>单位</th>
        <th>部门</th>
        <th>操作</th>
    </tr>
    </thead>
    {% for foo in data %}
	     <tr id="{{ foo.id }}">
            <td>{{ foo.id }}</td>
            <td>{{ foo.Zcbh }}</td>
            <td >{{ foo.Bgr }}</td>
            <td width="506px">{{ foo.Brand }}</td>
            <td>{{ foo.Count }}</td>
            <td>{{ foo.Price }}</td>
            <td>{{ foo.get_Status_display }}</td>
            <td>{{ foo.gtime|date:"Y-m-d" }}</td>
            <td>{{ foo.get_Atype_display }}</td>
            <td>{{ foo.Aunit }}</td>
            <td>{{ foo.get_Dname_display }}</td>
            <td width="72px"><a href="javascript:;" onclick="zhezhao({{ foo.id }})">编辑</a>|
                <a href="javascript:;" onclick="del({{ foo.id }})">删除</a></td>
        </tr>
    {% endfor %}
</table>
<div class="inline pull-right page">
    {{ zongyeshu }} 条记录 1/{{ zpage }} 页  <a href="http://127.0.0.1:8000/page/{{ spage }}/">上一页</a>
        {% if y2 %}
         <a href="http://127.0.0.1:8000/page/{{ y2 }}/">{{ y2 }}</a>
       {% endif %}
        <a href="http://127.0.0.1:8000/page/{{ y }}/">{{ y }}</a>
        <a href="http://127.0.0.1:8000/page/{{ y1 }}/">{{ y1 }}</a>
    <a href="http://127.0.0.1:8000/page/{{ cpage }}">下一页</a> <a href="http://127.0.0.1:8000/page/{{ zpage }}/">最后一页</a>
</div>

    <h1>{{ foo.Bgr }}</h1>

		</div>



		<div id="test">
                <div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×
				</button>
				<h4 class="modal-title" id="myModalLabel">
                    修改资产信息
				</h4>
			    </div>
    <form action="#" method="post" class="definewidth m20">
    <table class="table table-bordered ">
    <tr>
        <td ><label>资产标签</label></td>
        <td><input id="zcbq" type="text" name="zcbq"/></td>
        <td><label>保管人</label></td>
        <td><input id="name" type="text" name="bgr"/></td>
    </tr>

    <tr>
        <td ><label>品牌</label></td>
        <td><input id="brand" type="text" name="brand"/></td>
         <td><label>数量</label></td>
        <td><input id="num" type="text" name="num"/></td>
    </tr>

    <tr>
        <td><label>资产原值</label></td>
        <td><input id="yuanzhi" type="text" name="realname"/></td>
        <td><label>购进时间</label></td>
        <td><input id="gdate" type="date" name="gdate"/></td>
    </tr>

    <tr>
        <td><label>资产类型</label></td>
         <td>
<select class="tab" id="atype" name="email">
    <option  value="台式电脑">台式电脑</option>
    <option  value="笔记本电脑">笔记本电脑</option>
</select >
        </td>
                <td><label>单位</label></td>
        <td><input id="auint" type="text" name="auint"/></td>

    </tr>


     <tr>
        <td><label>部门</label></td>
         <td>
 <select class="tab" id="dept" name="dept" >
    <option  value="销售部">销售部</option>
    <option  value="采购部">采购部</option>
    <option  value="信息技术部">信息技术部</option>
    <option  value="客服部">客服部</option>
    <option  value="市场部">市场部</option>
    <option  value="事业加盟部">事业加盟部</option>
    <option  value="战略研究部">战略研究部</option>
    <option  value="人事行政部">人事行政部</option>
    <option  value="财务部">财务部</option>
    <option  value="仓储配送部">仓储配送部</option>
</select ></td>
         <td><label>资产ID</label></td>
        <td><input id="id" type="text" name="id"/></td>
    </tr>

    <tr>
        <td><label>状态</label></td>
        <td>
<select class="tab" id="status" name="status">
    <option  value=0>闲置</option>
    <option  value=1>在用</option>
</select >
        </td>
                <td class="tableleft"></td>
        <td>
            <button  id="sub" class="btn btn-primary" type="button">保存</button> &nbsp;&nbsp;<button type="button" class="btn btn-success" name="backid" id="backid">返回列表</button>
        </td>
    </tr>


    </table>
</form>
</div>















</div>
<div class="modal-content" id="del">
			<div class="modal-header">
				<button type="button" id="quit" class="close" data-dismiss="modal" aria-hidden="true">×
				</button>
				<h4 class="modal-title" id="myModalLabel">
					确定删除当前资产吗
				</h4>
			</div>
			<div class="modal-body" id="modalbody">

			</div>
			<div class="modal-footer">
				<button type="button" id="quit1" class="btn btn-default" data-dismiss="modal">关闭
				</button>
				<button type="button" id="tidel" class="btn btn-primary">
					确认
				</button>
			</div>
		</div>





<script>
  function zhezhao(foo) {
      var a = $('#'+foo)
      var id = a.children().eq(0).text();
      var zcbq = a.children().eq(1).text();
      var bgr = a.children().eq(2).text();
      var Brand = a.children().eq(3).text();
      var num = a.children().eq(4).text();
      var yuanzhi = a.children().eq(5).text();
      var status = a.children().eq(6).text();
      var gdate = a.children().eq(7).text();
      var atype = a.children().eq(8).text();
      var auint = a.children().eq(9).text();
      var dept = a.children().eq(10).text();
      var dept1 = a.children().eq(11).text();
      $('#name').val(bgr);
      $('#zcbq').val(zcbq);
      $('#brand').val(Brand)
      $('#num').val(num)
      $('#yuanzhi').val(yuanzhi)
      $('#status').val(status)
      $('#gdate').val(gdate)
      $('#atype').val(atype)
      $('#auint').val(auint)
      $('#dept').val(dept)
      $('#id').val(id)
      var div1 = document.getElementById('test');

        div1.style.display='block';
  };

  $('#backid,.close').click(function () {
    var div1 = document.getElementById('test');
    div1.style.display='none';
  })


  		    $('#sub').click(function () {


                $.ajax({
                    url:'/edit/',
                data:{Aname: $('#name').val(),
                zcbq:$('#zcbq').val(),
                brand:$('#brand').val(),
                num:$('#num').val(),
                yuanzhi:$('#yuanzhi').val(),
                status:$('#status').val(),
                gdate:$('#gdate').val(),
                atype:$('#atype').val(),
                auint:$('#auint').val(),
                dept:$('#dept').val(),
                id:$('#id').val()
                    },
                    type:'POST',
                    success:function (collback) {
                        var obj = jQuery.parseJSON(collback);
                        if (obj.status == 'OK'){
                            var div1 = document.getElementById('test');
                            div1.style.display='none';
                            alert('OK');
                            window.location.reload();
                        }else {
                            alert('更新失败')
                        }

                    }

                })
            })

  function del(foo) {
      var a = $('#' + foo)
      var zcbh = a.children().eq(1).text();
      var id = a.children().eq(0).text();
      var div1 = document.getElementById('del');
      div1.style.display='block';
      $('#modalbody').html(zcbh);
        $('#tidel').click(function () {
      $.ajax({
          url:'/del/',
          data:{aid:id},
          type:'POST',
          success:function (collback) {
              var obj = jQuery.parseJSON(collback);
               if (obj.status == 'OK'){
                            $('#del').css("display","none")
                            alert('OK');
                            window.location.reload();

                        }else {
                            alert('更新失败')
                        }


          }


      })
  })
  }

  $('#quit,#quit1').click(function () {
       var div1 = document.getElementById('del')
      div1.style.display='none';

  })


</script>

templates/search.html
<head>

       <link rel="stylesheet" type="text/css" href=/static/assets/css/boot3.css />
    <link rel="stylesheet" type="text/css" href= /static/Css/bootstrap-responsive.css/>
    <link rel="stylesheet" type="text/css" href=/static/Css/style.css />
    <script type="text/javascript" src=/static/assets/js/jquery.js></script>
    <style>
        .table{
            font-size: 5px;
        }
                       .tab{
            width: 152px;
            height: 23px;
        }
        #test{
            position: absolute;
            left: 302px;
            top: 167px;
            width: 50%;
            height: 50%;
            background-color: #F0F0F0;
            display: none;
            opacity: 1;

        }
         .modal-content{
            position: absolute;
            left: 392px;
            top: 187px;
            width: 30%;
            height: 25%;
            opacity: 1;
            display: none;

        }
    </style>
</head>

<div  class="span13">
<form class="form-inline definewidth m20" action="/search/" method="post">
    <div class="search">
    <select class="selectpicker" name="tiaojian" style="width: 87px;height: 24px">
         <option value="b">保管人</option>
         <option value="z">资产编号</option>
    </select>
    </div>
   <div>
    <input type="text" name="username" id="username"class="abc input-default" placeholder="" value="">&nbsp;&nbsp;
    <button id="search" type="submit" class="btn btn-primary">查询</button>&nbsp;&nbsp; <button type="button" class="btn btn-success" id="addnew"><a style="text-decoration: none;color:#e6f2ff" href="http://127.0.0.1:8000/page/1/">返回</a></button>
    </div>
</form>
<table class="table table-bordered table-hover definewidth m10" >
    <thead>
    <tr>
        <th>ID</th>
        <th>资产标签</th>
        <th>保管人</th>
        <th>品牌</th>
        <th>数量</th>
        <th>资产原值</th>
        <th>使用状态</th>
        <th>购进时间</th>
        <th>资产类型</th>
        <th>单位</th>
        <th>部门</th>
        <th>操作</th>
    </tr>
    </thead>
    {% for foo in data %}
	     <tr id="{{ foo.id }}">
            <td>{{ foo.id }}</td>
            <td>{{ foo.Zcbh }}</td>
            <td >{{ foo.Bgr }}</td>
            <td width="506px">{{ foo.Brand }}</td>
            <td>{{ foo.Count }}</td>
            <td>{{ foo.Price }}</td>
            <td>{{ foo.get_Status_display }}</td>
            <td>{{ foo.gtime|date:"Y-m-d" }}</td>
            <td>{{ foo.get_Atype_display }}</td>
            <td>{{ foo.Aunit }}</td>
            <td>{{ foo.get_Dname_display }}</td>
            <td width="72px"><a href="javascript:;" onclick="zhezhao({{ foo.id }})">编辑</a>|
                <a href="javascript:;" onclick="del({{ foo.id }})">删除</a></td>
        </tr>
    {% endfor %}
</table>



		</div>

		<div id="test">
                <div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×
				</button>
				<h4 class="modal-title" id="myModalLabel">
                    修改资产信息
				</h4>
			    </div>
    <form action="#" method="post" class="definewidth m20">
    <table class="table table-bordered ">
    <tr>
        <td ><label>资产标签</label></td>
        <td><input id="zcbq" type="text" name="zcbq"/></td>
        <td><label>保管人</label></td>
        <td><input id="name" type="text" name="bgr"/></td>
    </tr>

    <tr>
        <td ><label>品牌</label></td>
        <td><input id="brand" type="text" name="brand"/></td>
         <td><label>数量</label></td>
        <td><input id="num" type="text" name="num"/></td>
    </tr>

    <tr>
        <td><label>资产原值</label></td>
        <td><input id="yuanzhi" type="text" name="realname"/></td>
        <td><label>购进时间</label></td>
        <td><input id="gdate" type="date" name="gdate"/></td>
    </tr>

    <tr>
        <td><label>资产类型</label></td>
        <td><input id="atype" type="text" name="email"/></td>
                <td><label>单位</label></td>
        <td><input id="auint" type="text" name="auint"/></td>
    </tr>


     <tr>
        <td><label>部门</label></td>
         <td>
 <select class="tab" id="dept" name="dept" >
    <option  value="销售部">销售部</option>
    <option  value="采购部">采购部</option>
    <option  value="信息技术部">信息技术部</option>
    <option  value="客服部">客服部</option>
    <option  value="市场部">市场部</option>
    <option  value="事业加盟部">事业加盟部</option>
    <option  value="战略研究部">战略研究部</option>
    <option  value="人事行政部">人事行政部</option>
    <option  value="财务部">财务部</option>
    <option  value="仓储配送部">仓储配送部</option>
</select ></td>
         <td><label>资产ID</label></td>
        <td><input id="id" type="text" name="id"/></td>
    </tr>

    <tr>
        <td><label>状态</label></td>
        <td>
<select class="tab" id="status" name="status">
    <option  value=0>闲置</option>
    <option  value=1>在用</option>
</select >
        </td>
                <td class="tableleft"></td>
        <td>
            <button  id="sub" class="btn btn-primary" type="button">保存</button> &nbsp;&nbsp;<button type="button" class="btn btn-success" name="backid" id="backid">返回列表</button>
        </td>
    </tr>


    </table>
</form>
</div>
</div>
<div class="modal-content" id="del">
			<div class="modal-header">
				<button type="button" id="quit" class="close" data-dismiss="modal" aria-hidden="true">×
				</button>
				<h4 class="modal-title" id="myModalLabel">
					确定删除当前资产吗
				</h4>
			</div>
			<div class="modal-body" id="modalbody">

			</div>
			<div class="modal-footer">
				<button type="button" id="quit1" class="btn btn-default" data-dismiss="modal">关闭
				</button>
				<button type="button" id="tidel" class="btn btn-primary">
					确认
				</button>
			</div>
		</div>


</div>

<script>
  function zhezhao(foo) {
      var a = $('#'+foo)
      var id = a.children().eq(0).text();
      var zcbq = a.children().eq(1).text();
      var bgr = a.children().eq(2).text();
      var Brand = a.children().eq(3).text();
      var num = a.children().eq(4).text();
      var yuanzhi = a.children().eq(5).text();
      var status = a.children().eq(6).text();
      var gdate = a.children().eq(7).text();
      var atype = a.children().eq(8).text();
      var auint = a.children().eq(9).text();
      var dept = a.children().eq(10).text();
      var dept1 = a.children().eq(11).text();
      $('#name').val(bgr);
      $('#zcbq').val(zcbq);
      $('#brand').val(Brand)
      $('#num').val(num)
      $('#yuanzhi').val(yuanzhi)
      $('#status').val(status)
      $('#gdate').val(gdate)
      $('#atype').val(atype)
      $('#auint').val(auint)
      $('#dept').val(dept)
      $('#id').val(id)
      var div1 = document.getElementById('test');

        div1.style.display='block';
  };

  $('#backid,.close').click(function () {
    var div1 = document.getElementById('test');
    div1.style.display='none';
  })


  		    $('#sub').click(function () {


                $.ajax({
                    url:'/edit/',
                data:{Aname: $('#name').val(),
                zcbq:$('#zcbq').val(),
                brand:$('#brand').val(),
                num:$('#num').val(),
                yuanzhi:$('#yuanzhi').val(),
                status:$('#status').val(),
                gdate:$('#gdate').val(),
                atype:$('#atype').val(),
                auint:$('#auint').val(),
                dept:$('#dept').val(),
                id:$('#id').val()
                    },
                    type:'POST',
                    success:function (collback) {
                        var obj = jQuery.parseJSON(collback);
                        if (obj.status == 'OK'){
                            var div1 = document.getElementById('test');
                            div1.style.display='none';
                            alert('OK');
                        }else {
                            alert('更新失败')
                        }

                    }

                })
            })

function search(foo) {
                $.ajax({
                    url:'search/',
                    data:{conditon:$('#username').val()},
                    type:'POST',
                    success:function () {

                    }

                })

}
function del(foo) {
      var a = $('#' + foo)
      var zcbh = a.children().eq(1).text();
      var id = a.children().eq(0).text();
      var div1 = document.getElementById('del');
      div1.style.display='block';
      $('#modalbody').html(zcbh);
        $('#tidel').click(function () {
      $.ajax({
          url:'/del/',
          data:{aid:id},
          type:'POST',
          success:function (collback) {
              var obj = jQuery.parseJSON(collback);
               if (obj.status == 'OK'){
                            $('#del').css("display","none")
                            alert('OK');
                            window.location.reload();

                        }else {
                            alert('更新失败')
                        }


          }


      })
  })
  }
$('#quit,#quit1').click(function () {
       var div1 = document.getElementById('del')
      div1.style.display='none';

  })
</script>